services:
  mongodb:
    build: ./db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: swapi
    volumes: 
      - './db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro'
    restart: always
  mongodb-seed:
    build: ./seed
    depends_on:
      - mongodb
  backend:
    build: backend
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /backend/src
        - action: rebuild
          path: ./backend/package.json
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: data
      MONGO_HOST: mongodb://user:password@mongodb:27017/swapi
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    restart: on-failure
  frontend:
    build: frontend
    environment:
      API_HOST: backend:5000/api/
    ports:
      - 5173:5173
    volumes: 
      - './frontend:/app'
      - '/app/node_modules/'
    depends_on:
      - backend
    

   